version: "3.3"
services:
  mongo:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    network_mode: mongodb-network
    container_name: mongodb
    image: mongo
