# Create a new note

POST http://localhost:3000/api/notes HTTP/1.1
Content-Type: application/json

{
	"title": "2nd test note",
	"content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dolor turpis, tempor vel eleifend et, tincidunt vitae arcu."
}