import Head from "next/head";
import { useRouter } from "next/router";

type Props = {};

const HeadWrapper = (props: Props) => {
	const router = useRouter();

	const currentPage =
		router.pathname === "/"
			? "Home"
			: router.pathname[1].toUpperCase() + router.pathname.slice(2);

	return (
		<Head>
			<title>{`Notes App | ${currentPage}`}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export { HeadWrapper as Head };

